set-option -g prefix C-a
bind e setw synchronize-panes on
bind E setw synchronize-panes off
# Switch between zoomed panes
bind -r a select-pane -t .+1 \;  resize-pane -Z
# The following four commands enable mouse events
set -g mouse on
set -s default-terminal "tmux-256color"
set-window-option -g aggressive-resize off
set-option -g renumber-windows on

# Use v to trigger selection    
bind-key -T copy-mode-vi v send-keys -X begin-selection
# Use y to yank current selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'moon' # Options are 'main', 'moon' or 'dawn'
set -g @plugin 'erikw/tmux-dark-notify'
set -g @plugin 'tmux-plugins/tpm'

# set -g @dark-notify-theme-path-light '$HOME/.tmux/plugins/tmux/rose-pine.tmux'
# set -g @dark-notify-theme-path-dark '$HOME/.tmux/plugins/nord-tmux/src/nord.conf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$HOME/.tmux/plugins/tpm/tpm"

unbind -n C-l
